/*
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWXXWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMXd:xNWKc..c0WNxcdXMMMMMWMMMMMMMMMM
MMMMMMMMMMMMMWWO; .l0x.    'x0l. ,OWMMMMMMMMMMMMMM
MMMMMMMMMMMMMXl. ,kO;  :xx:  ;Ok, .lXMWMMMMMMMMMMM
MMMMMMMMMMMW0, .lXWk. .xNNx. .OWXl. ,0MMMMMMMMMMMM
MMMMMMMMMMMM0, .dNMW0; .,,. ;0WMWd. ;0MMMMMMMMMMMM
MMMMMMMMNKKKKk' .oKKKO:    :OKK0o. 'kKKKKNWMMMMMMM
MMMMMMMWO,.....   .....    .....   .....,OWMMMMMMM
MMMMMMMMWk.  ;dd:. .cddddddddc. .:dd;  .kWMMMMMMMM
MMMMMMMMMMO, .xWNd. ;0MMMMMMK; .dNNx. ,OMMMMMMMMMM
MMMMMMMMMMM0;.lXWNx. ,0WMMW0, .xWMXc.;KMMMMMMMMMMM
MMMMMMMMMMMMXKWMMMWk' .OWWO. 'kWMMMNKNMWMMMMMMMMMM
MMMMMMMMMMMMMMMMMXXW0, .::. ,OWXXWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWx''kWK;    ;KWx''xWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMM0; .dNd.  .dNd. ,0WMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWK: .,. .. .'. :KMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXl.  cOOc   lXMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNo'oNMMNo'oNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNXWMMMMWXWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
*/

document.addEventListener("DOMContentLoaded", function() {
    let colors = [
        '#FF0000', '#00FF00', '#0000FF', '#FFFF00', '#FF00FF', '#00FFFF', 
        '#FF4500', '#32CD32', '#1E90FF', '#FFD700', '#EE82EE', '#7FFF00', 
        '#ADFF2F', '#FF6347', '#BA55D3'
    ];

    let index = 0;

    setInterval(function() {
        document.body.style.backgroundColor = colors[index];
        index = (index + 1) % colors.length;
    }, 50);
});
